-- Nagad Deploy Console — registry-db schema.
-- Portable DDL: runs on PostgreSQL 15 and on H2 (PostgreSQL compatibility mode).
-- "group" is a reserved word, so the column is named group_name throughout.

CREATE TABLE app_user (
    username    VARCHAR(64)  PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    email       VARCHAR(160) NOT NULL,
    role        VARCHAR(16)  NOT NULL,          -- superadmin | operator | viewer
    scope       VARCHAR(512) NOT NULL,          -- 'all' or comma-separated wrapper groups
    perm_r      BOOLEAN      NOT NULL DEFAULT TRUE,
    perm_w      BOOLEAN      NOT NULL DEFAULT FALSE,
    perm_x      BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Demo credential store. In production this is an SSO subject id, never a raw hash column.
    password_hash VARCHAR(256) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE promotion (
    id            VARCHAR(16)  PRIMARY KEY,      -- PR-1042
    app           VARCHAR(64)  NOT NULL,
    group_name    VARCHAR(64)  NOT NULL,
    src_host      VARCHAR(64)  NOT NULL,
    jar           VARCHAR(160) NOT NULL,
    git_hash      VARCHAR(40)  NOT NULL,
    prev_hash     VARCHAR(40),
    branch        VARCHAR(64),
    size_label    VARCHAR(32),
    requested_by  VARCHAR(64)  NOT NULL,
    requested_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(16)  NOT NULL,         -- pending | approved | denied | deployed
    decided_by    VARCHAR(64),
    decided_at    TIMESTAMP,
    note          VARCHAR(512),
    CONSTRAINT fk_promotion_requester FOREIGN KEY (requested_by) REFERENCES app_user(username)
);

CREATE INDEX idx_promotion_status ON promotion(status);
CREATE INDEX idx_promotion_group_app ON promotion(group_name, app);

CREATE TABLE jar_registry (
    app         VARCHAR(64)  NOT NULL,
    group_name  VARCHAR(64)  NOT NULL,
    jar         VARCHAR(160) NOT NULL,
    prod_hash   VARCHAR(40),
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  VARCHAR(64),
    PRIMARY KEY (app, group_name)
);

CREATE TABLE deployment (
    id            VARCHAR(24)  PRIMARY KEY,
    promotion_id  VARCHAR(16),
    group_name    VARCHAR(64)  NOT NULL,
    hosts         VARCHAR(256) NOT NULL,
    apps          VARCHAR(256) NOT NULL,
    actions       VARCHAR(64)  NOT NULL,         -- stop,deploy,start
    started_by    VARCHAR(64)  NOT NULL,
    started_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration      VARCHAR(16),
    result        VARCHAR(16),                   -- ok | failed | partial | running
    before_after  TEXT,                          -- JSON: per-host before/after hashes
    log_excerpt   TEXT,
    CONSTRAINT fk_deployment_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE INDEX idx_deployment_started ON deployment(started_at);

-- Append-only compliance record. One row per fetch / approve / deny / deploy.
CREATE TABLE audit_log (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor   VARCHAR(64)  NOT NULL,
    verb    VARCHAR(32)  NOT NULL,               -- login | fetch | approve | deny | deploy | rollback
    target  VARCHAR(160) NOT NULL,
    detail  VARCHAR(1024)
);

CREATE INDEX idx_audit_ts ON audit_log(ts);
